# This is a basic workflow to help you get started with Actions

name: lfm

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get last.fm
        run: curl "http://ws.audioscrobbler.com/2.0/?method=user.getTopAlbums&user=Tenebre55&period=7d&limit=10&api_key=ac6bef34d4bbee1eb30eb15d09488c19&format=json" >> README.md
      - name: Commit changes
        run: |
          git add README.md
          git commit -m "Updated Readme from last.fm"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
