# This is a basic workflow to help you get started with Actions

name: lfm

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get last.fm
        with: key: ${{ secrets.API_KEY }}
        run: curl 'http://ws.audioscrobbler.com/2.0/?method=user.getTopAlbums&user=Tenebre55&period=1month&limit=10&api_key=${key}$&format=json' | python ./lfm.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Updated Readme from last.fm"
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
